services:
  postgres:
    image: bitnami/postgresql:15
    container_name: postgres
    environment:
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=internship_project
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/bitnami/postgresql
    networks:
      - app-network

  spark-master:
    image: our-own-apache-spark:3.4.0
    container_name: spark-master
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master
      - SPARK_SUBMIT_ARGS=--jars /opt/spark/jars/clickhouse-jdbc-0.6.0.jar,/opt/spark/jars/postgresql-42.2.29.jre7.jar
      - SPARK_CLASSPATH=/opt/spark/jars/clickhouse-jdbc-0.6.0.jar:/opt/spark/jars/postgresql-42.2.29.jre7.jar
    ports:
      - "7077:7077"
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - postgres

  spark-worker:
    image: our-own-apache-spark:3.4.0
    container_name: spark-worker
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=2G
      - SPARK_DRIVER_MEMORY=2G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker
      - SPARK_SUBMIT_ARGS=--jars /opt/spark/jars/clickhouse-jdbc-0.6.0.jar,/opt/spark/jars/postgresql-42.2.29.jre7.jar
      - SPARK_CLASSPATH=/opt/spark/jars/clickhouse-jdbc-0.6.0.jar:/opt/spark/jars/postgresql-42.2.29.jre7.jar
    ports:
      - "9091:8080"
      - "7000:7000"
    networks:
      - app-network
    depends_on:
      - spark-master

  spark-submit:
    image: our-own-apache-spark:3.4.0
    container_name: spark-submit
    depends_on:
      - spark-master
      - spark-worker
      - clickhouse
    networks:
      - app-network
    environment:
      - SPARK_WORKLOAD=submit
      - SPARK_SUBMIT_ARGS=--jars /opt/spark/jars/clickhouse-jdbc-0.6.0.jar,/opt/spark/jars/postgresql-42.2.29.jre7.jar
      - SPARK_CLASSPATH=/opt/spark/jars/clickhouse-jdbc-0.6.0.jar:/opt/spark/jars/postgresql-42.2.29.jre7.jar
    entrypoint: >
      /opt/spark/bin/spark-submit
      --master spark://spark-master:7077
      --deploy-mode client
      --jars /opt/spark/jars/clickhouse-jdbc-0.6.0.jar,/opt/spark/jars/postgresql-42.2.29.jre7.jar
      /opt/transform.py

  #      --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.4.0

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse/create_clickhouse_tables.sh:/docker-entrypoint-initdb.d/create_clickhouse_tables.sh
    networks:
      - app-network

  data-generator:
    build:
      context: ./data_generator
    container_name: data_generator
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres_data:
  spark-apps:
  clickhouse_data:

networks:
  app-network:
    driver: bridge
