global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'prometheus:9090' ]

  - job_name: 'cadvisor'
    static_configs:
      - targets: [ 'cadvisor:8080' ]

  - job_name: 'node-exporter'
    static_configs:
      - targets: [ 'node-exporter:9100' ]

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: [ 'postgres-exporter:9187' ]

  - job_name: 'clickhouse-exporter'
    static_configs:
      - targets: [ 'clickhouse-exporter:9116' ]

  - job_name: 'spark'
    metrics_path: /metrics
    static_configs:
      - targets: [ 'spark-master:8000', 'spark-worker:8000', 'spark-submit:8000' ]
